### ISSUE TITLE
Sorting edited columns

### ISSUE THREAD

**Issue by bart** [yajra/laravel-datatables-oracle#3]
Sorry @yajra, but I have another question concerning sorting.
I selected some Ids for a hand full of columns which I edited afterwards.

Here is an example:

```
$projects = Project::select([
	'id',
	'username',
	'identity',
]);

return Datatables::of($projects)
	->editColumn('identity', function($projects) {
		// Some magic number adaption
		$newValue = $this->getIdent($projects->identity);
		return $newValue
	})->make();
```

The problem on this is approach is that sorting the datatables uses the selected values from the $projects object and doesn't take edited columns into account, right?

So if I have 3 entries where the identity field in the database are 10, 20 and 30. After some magic number adaption they will be presented as 901, 800, 1904. So when I sort the results, I get the wrong order, right? Any solution for that?

Thanks and kind regards!

**Comment by yajra** [comment]
Since sorting is done on the database level, you would have to put the logic on getting `identity` field on the database side.  You can either create a database view or function to get the identity for sorting to work for your case. 

On the other hand, I mostly disable the sorting function whenever I encounter this case since it's computed.

Regards!
